#SPDX-License-Identifier: MIT-0
---
# tasks file for finisher

- name: Recursively remove directory
  file:
    path: /home/scanner/{{ item.name }}
    state: absent
  loop: "{{ repos }}"
  become: true