name: Defect dojo integration and scanner

on:
  push:
    branches:
      - main

jobs:
  integrate:
    runs-on: defectdojo
    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Publish report
        id: import-scan
        uses: ivanamat/defectdojo-import-scan@v1
        with:
          token: ${{ secrets.DEFECTOJO_TOKEN }}
          defectdojo_url: ${{ secrets.DEFECTOJO_URL }}
          file: zap-web.xml
          scan_type: ZAP Scan
          engagement: 1

      - name: Show response
        run: |
          set -e
          printf '%s\n' '${{ steps.import-scan.outputs.response }}'
